Update links.yml
Signed-off-by: Glenn Jocher <glenn.jocher@ultralytics.com>

diff --git a/.github/workflows/links.yml b/.github/workflows/links.yml
--- a/.github/workflows/links.yml
+++ b/.github/workflows/links.yml
@@ -33,7 +33,7 @@ jobs:
           retry_delay_seconds: 60
           retries: 2
           run: |
-            # set -o pipefail  # This makes the pipeline return the exit code of the first failing command
+            set -o pipefail  # preserve exit code from lychee command in pipeline
             lychee \
             --scheme 'https' \
             --accept 403,429,500,502,999 \
@@ -53,6 +53,7 @@ jobs:
           retry_delay_seconds: 60
           retries: 2
           run: |
+            set -o pipefail  # preserve exit code from lychee command in pipeline
             lychee \
             --scheme 'https' \
             --accept 429,999 \
